version: "3"
services:
  app:
    container_name: openpad-app
    image: guizo/docker-laravel
    ports:
      - 8081:80
    volumes:
      - ./:/var/www/html
    environment:
      - TZ=America/Sao_Paulo
  db:
    container_name: openpad-db
    image: mysql:5.7
    ports:
      - 33061:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openpad
volumes:
  db_data:
    driver: local
