version: "3"
services:
  openpad-laravel-app:
    container_name: openpad-laravel-app
    image: openpad-laravel-app
    build:
      context: ./
      dockerfile: app.dockerfile
    ports:
      - 8081:80
    volumes:
      - ./laravel:/var/www/html
    environment:
      - TZ=America/Sao_Paulo
  openpad-laravel-db:
    container_name: openpad-laravel-db
    image: mysql:5.7.18
    ports:
      - "33061:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openpad-laravel-db